services:
  - type: web
    name: whatsapp-vtu-bot
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: ACCESS_TOKEN
        sync: false
      - key: VERIFY_TOKEN
        sync: false
      - key: PHONE_NUMBER_ID
        sync: false
